sudo: required
services:
- docker
addons:
  apt:
    packages:
    - httpie
script:
- "./travis-ci.sh"
env:
  global:
  - secure: qGNW/t4tiIr7B3yI4mgzQ5e6Ew1xekv9KwLXaGDVWtQpwalLHc1G8f0Ew5qcQZyGGDcCemOR2ytCb+1f0tK/lSMLedGEAiScXSt9ZVb72onSiOUiHAtaFjiNYUgI8Z0B09l1+WOJnkoNtpU/bzVKYN6CW3ZuOYK/Z26LhkSkFpyBLDBQGpHs1xiTfMSyGcQ3iiQTlznlDkExRxVWGA/kBDUSOlvVisWnqbZ9xDT7YtyeGXuXtkYb+claMHOaZIH4oGnUVAFLShGQwsGrT2EASOC3S7zwJaEPsqHTZJFw0UWbnplfcgg9nh4UbwKxsT2gLo1PjSXBHNHwSB7BM4npHCk6B68W4O4zx/mz8/WvVkwjJLDKyGQ2/SoojW5FKTWnEdE0mnr3urSFb2NwXLGfc8a0d5IZfmXg2L3+UDE9ijZtaCp8681GyN6XdTCaRA2Ic7fR9i8lmPesTEiPeqTxTSeO2CfRfBEZP783iKRXv0FscXfjj7BBr2Q3M+OeBeCcSw5QXaQMnjY6H2vYwea/NkgrOtA0eedm5ttIngqdBjEBL4/LUSzM5SS/kFA5OP5oJ3uJ5Tgw0XK5fTbDUDaKQsHi7XsNxnG+aSkO1i1WLrFam3ZyhkNF2C33/pnTS0hPFD/fszDUW4O1gDIzQ7lgJPPaNdLV0rJHBTvEAPjHnbc=
  - secure: pdISBxa6DOrPZGZl0ZQRuSM81DDbiwGoL/Kr2UzXI7/pnuIMKoybbxdP/nSEeJMYACw09sR25fa7TaDzpYq9rt6LGxTm/hON870qZUjYis8ecOnhOeMO/T8BSebxKg59QxUuidcenHhsGionmhmBcWt08vceMjIwDeefwqjBwCPrgmwcghaBfJgEU+t95gAYemLqlxkXa+zKaV3eZAP7P5Zc/bHPkqpT+JKM99mf6SMRpekhNKDdXLkGuwGJ2t1efdALOQtNJd9g/IL0B7nm7+XfrXrWEwWH9RIliNe4vEM+sdpzcCtyBrNg8h34KLSHmyIkLW/aQ/6jxqrl58zS36X6Ki8fG1j5jTbkbjTZ+Qq66MRvGwg+FF5r3yt0M4eUt3vwh9kw+bkE1BJ+zZQiEYSuodsVJpN4MtfpW+MqXiOqus0Z0+5feQYR9pTegrYtfGylvQOx8ifJYD3zCTvz4i+ZOlVoy7DlWwx+C5nim5R7NZHI+qWE2hY12UEUcWqS3mMOyykCL3CG3yplWlF17Bpmnpgc5hAwKa9SZ74RCt6zBaWcmGcpRtEogBsDPbi6ohdo1HbHig2bK32sjdsqSW3QZ+eySBLgLlJ509bNWYTgUDNQvqXWfz9w6zrC6goeBJ+dJ5Qivr6dBr4bmATUU1LFJqrmTnU9CapQJgkYlfY=
